# Generated by Django 4.1.6 on 2023-02-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(db_index=True, max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('published_at', models.DateTimeField()),
                ('channelId', models.CharField(max_length=64)),
                ('channelTitle', models.CharField(max_length=64)),
                ('thumbnailsUrl', models.URLField()),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
